### PR TITLE
Add opengraph/

### PR DESCRIPTION
**Pull request by 1robertrb**
Add an `opengraph/` directory that contains png images
optimized for the [opengraph protocol](https://ogp.me/).

The opengraph protocol determines how a URL preview will
appear on Facebook, Mastodon and other popular websites.
Twitter supports the opengraph protocol to a certain extent,
but [Twitter cards](https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started) seem to be preferred and have better support.

The `bin/build-opengraph` shell script creates the contents
of the opengraph/ directory.

### CODE REVIEW

**Comment by gyenabubakar** [comment]
@0x1eef This is really good. I noticed you made a few pushes after opening this PR. Is this ready to be merged?

**Comment by 0x1eef** [comment]
@gyenabubakar 

Not sure if we can improve further or not. 
Here are some examples that use an opengraph preview tool:
* https://robolly.com/open-graph-preview/?url=https://al-quran.reflectslight.io/en/al-fatihah/
* https://robolly.com/open-graph-preview/?url=https://al-quran.reflectslight.io/en/al-baqarah/
* https://robolly.com/open-graph-preview/?url=https://al-quran.reflectslight.io/en/ghafir/

Edit:
Seems to be that the glyph for Surah Ghafir is not vertically-centered as well as the others.
Maybe we could handle that one specially, and maybe others as well.
I'm thinking of adding `opengraph/40.options` that would define custom a --top option that would do a better job at centering the glyph vertically.

**Comment by 0x1eef** [comment]
I hope the glyph for Surah Ghafir has been improved after [this commit](https://github.com/gyenabubakar/surah-name-glyphs/commit/9ad1482331aeddf127bf799400e21d57b247744a). There could be other glyphs that should be treated specially, I haven't had the chance to go through all of them yet.

**Comment by 0x1eef** [comment]
@gyenabubakar 

I will hand it over to you from here. 
For the most part I think we're good. 
If I find anything lacking I can open another PR.

**Comment by 0x1eef** [comment]
@gyenabubakar 

I had a chance to test on mastodon, and there's still room for improvement.
Please hold off on merging for now.

**Comment by 0x1eef** [comment]
:wave: @gyenabubakar Ready for another review. Haven't achieved perfection but this seems good enough for now. I can work on the perfect alignment in further PRs.

**Review by gyenabubakar — APPROVED** [review]
Merging. Thanks @0x1eef. And my apologies for the late, late response.

**Comment by 0x1eef** [comment]
Thanks! :heart:

**Pull request merged**
